{
 "title": "TicketRush Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Booking Rate (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(booking_attempts_total[1m])",
     "legendFormat": "Attempts/sec"
    },
    {
     "expr": "rate(booking_success_total[1m])",
     "legendFormat": "Success/sec"
    },
    {
     "expr": "rate(booking_failed_oversold[1m])",
     "legendFormat": "Oversold/sec"
    }
   ]
  },
  {
   "title": "Cumulative Bookings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "booking_success_total", "legendFormat": "Total Success" },
    { "expr": "booking_failed_oversold", "legendFormat": "Total Blocked" }
   ]
  },
  {
   "title": "DB Query Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by(le) (rate(db_query_duration_seconds_bucket[1m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(db_query_duration_seconds_bucket[1m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(db_query_duration_seconds_bucket[1m])))",
     "legendFormat": "p99"
    }
   ]
  }
 ]
}